name: local
variables:
  - name: baseUrl
    value: http://localhost:8080/api
    enabled: true
    secret: false
    type: text
  - name: token
    value: ""
    enabled: true
    secret: false
    type: text
