info:
  name: Create Task
  type: http
  seq: 2

http:
  method: POST
  url: "{{dev}}/tasks"
  body:
    type: json
    data: |-
      {
        "title": "My new task",
        "description": "Task description here"
      }
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
