info:
  name: Delete Task
  type: http
  seq: 4

http:
  method: DELETE
  url: "{{baseUrl}}/tasks/:id"
  params:
    - name: id
      value: "1"
      type: path
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
